### DISCUSSION TITLE
math view field producing text property instead of number

### DISCUSSION THREAD

**Discussion by belaset** [mProjectsCode/obsidian-meta-bind-plugin#169] [Q&A] [answered]
I am building an exercise tracker with separate number inputs for cardio and strength minutes, and trying to total up my exercise minutes using a math view field. However, the property created by the view field is text rather than a number. Am I just missing something? What have I done wrong?

In addition to toggles to specify the type of exercise I've done, I have two number input fields:
```
cardio duration (minutes): `INPUT[number:ex.cardio.cardiominutes]`
strength duration (minutes): `INPUT[number:ex.strength.strengthminutes]`
```
I wanted a property for the total exercise minutes, so I did
```
VIEW[{ex.cardio.cardiominutes} + {ex.strength.strengthminutes}][math(hidden):extotal]`
```
In the frontmatter, I am seeing text:
```
extotal: "40"
```
rather than a number:
```
extotal: 40
```
And in reading mode, the property type is shown as text rather than a number. 

Because I am doing a math operation on two numbers, I expected it to produce a number, not text. (I'm trying to add all the "extotal" values in a dataview table on another page, but they won't add because they're not numbers.)

**Comment by belaset** [comment]
Here's the complete source view:

```
---
tags:
  - daily
obsidianEditingMode: live
extotal: "40"
ex:
  cardio:
    bike: true
    cardiominutes: 30
  strength:
    yoga: true
    strengthminutes: 10
---

biking: `INPUT[toggle:ex.cardio.bike]`   running: `INPUT[toggle:ex.cardio.run]` 
walking: `INPUT[toggle:ex.cardio.walk]`  other cardio: `INPUT[toggle:ex.cardio.other]`
cardio duration (minutes): `INPUT[number:ex.cardio.cardiominutes]`

weights: `INPUT[toggle:ex.strength.lift]` core: `INPUT[toggle:ex.strength.core]`  yoga: `INPUT[toggle:ex.strength.yoga]` 
strength duration (minutes): `INPUT[number:ex.strength.strengthminutes]`
`VIEW[{ex.cardio.cardiominutes} + {ex.strength.strengthminutes}][math(hidden):extotal]`
```

and reading view:
![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/68451495/748c42d1-a5a9-482f-b486-5bae5e61e9e9)
