### DISCUSSION TITLE
How to use Frontmatter properties with multiple words as bindTargets in buttons?

### DISCUSSION THREAD

**Discussion by workflowsguy** [mProjectsCode/obsidian-meta-bind-plugin#212] [Q&A] [answered]
Hello,

I am trying to update the value of a frontmatter date property "last used" through a meta-bind-button.
Even though the documentation states that using properties with spaces requires JavaScript bracket notation, it still does not update the actual property, but instead creates (and updates) a new property "last".

Am I doing something wrong or is this an issue with Meta Bind (I am not a JavaScript expert)?

This is the code  I am using (surrounding triple backticks of the code omitted):
```
meta-bind-button
label: "used"
hidden: false
id: "used"
style: default
actions:
  - type: updateMetadata
    bindTarget: ["last used"]
    evaluate: true
    value: new Date().toJSON()
```

Thanks!

**Comment by mProjectsCode** [comment, marked as answer]
try `bindTarget: "[\"last used\"]"`

**Comment by workflowsguy** [comment]
Excellent, thank you!

**Comment by didiowen** [comment]
Hi I have encountered a similar issue as I want to update the metadata with multiple entries, which means I have to close the entries by brackets, but I don't know how to do it correctly. Here's what I've tried:

```
meta-bind-button
label: "Share"
style: default
id: "share"
actions:
  - type: updateMetadata
    bindTarget: share
    evaluate: false
    value: true
  - type: updateMetadata
    bindTarget: categories
    evaluate: false
    value: "\[" + "<% tp.system.prompt("Please enter a category") %>" + "\]"
```

Can anyone help me?
