### DISCUSSION TITLE
Custom CSS Button help

### DISCUSSION THREAD

**Discussion by motion2082** [mProjectsCode/obsidian-meta-bind-plugin#446] [Q&A] [answered]
Does anyone know how to create a custom css style for a button?

The required style (default, primary, destructive, plain) seems to override any custom css in the snippets folder.

Alternately how can you add additonal styles so you don't need to use the four above?

**Comment by mProjectsCode** [comment, marked as answer]
What have you tried? How does your CSS selector look like?

The following example should work.
```yaml
style: primary
label: Open Meta Bind FAQ
class: my-css-class
action:
  type: command
  command: obsidian-meta-bind-plugin:open-faq
```

```css
.mb-button.my-css-class > button {
  rules: here;
}
```
