### DISCUSSION TITLE
Is there a better way to have buttons be in tables and not have the source code be elsewhere?

### DISCUSSION THREAD

**Discussion by AoifeHughes** [mProjectsCode/obsidian-meta-bind-plugin#596] [Q&A]
Is there a better way to have buttons be in tables and not have the source code be elsewhere? 

For example: 

```
---
project: VTE-BPA Paper
status: 🔄 Not-Started
priority: 🟡 Medium
tags:
  - vte-bpa-paper
created: 2025-06-27 11:36
time-completed: 
---

## Meta Data Buttons


| 📋 **Status**   | `BUTTON[not-started]` | `BUTTON[progress]` | `BUTTON[done]` | `BUTTON[archived]`   |
| --------------- | --------------------- | ------------------ | -------------- | -------------------- |
| 🎯 **Priority** | `BUTTON[low]`         | `BUTTON[medium]`   | `BUTTON[high]` | `BUTTON[ultra-high]` |


## 📝 Notes



## 📎 Resources



```meta-bind-button
label: 🔄 Not Started
id: not-started
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: status
  value: 🔄 Not-Started
  evaluate: false
```

```meta-bind-button
label: ⚡ In Progress
id: progress
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: status
  value: ⚡ In-Progress
  evaluate: false
```

```meta-bind-button
label: ✅ Done
id: done
hidden: true
style: default
actions:
  - type: updateMetadata
    bindTarget: status
    value: ✅ Done
    evaluate: false
  - type: updateMetadata
    bindTarget: time-completed
    value: new Date().toISOString().replace('T', ' ').substring(0, 16)
    evaluate: true
```

```meta-bind-button
label: 📦 Archived
id: archived
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: status
  value: 📦 Archived
  evaluate: false
```

```meta-bind-button
label: 🟢 Low
id: low
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: priority
  value: 🟢 Low
  evaluate: false
```

```meta-bind-button
label: 🟡 Medium
id: medium
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: priority
  value: 🟡 Medium
  evaluate: false
```

```meta-bind-button
label: 🔴 High
id: high
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: priority
  value: 🔴 High
  evaluate: false
```

```meta-bind-button
label: 🟣 Ultra-High
id: ultra-high
hidden: true
style: default
action:
  type: updateMetadata
  bindTarget: priority
  value: 🟣 Ultra-High
  evaluate: false
```

```
