### DISCUSSION TITLE
Shut up and take my money!

### DISCUSSION THREAD

**Discussion by stoilis** [mProjectsCode/obsidian-meta-bind-plugin#96] [General]
This is a great plugin, but it I don't see a way to show you my appreciation.

Please enable [github sponsorship](https://github.com/sponsors/accounts) or add [BuyMeACoffee](https://www.buymeacoffee.com/) links somewhere.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/873390/505c8da4-aad0-4de1-9c07-8012b3ff425e)

**Comment by mProjectsCode** [comment]
Thank you for wanting to support me, but I don't plan to accept donations for two reasons.

1. German tax laws
2. I want to keep this as a fun hobby, not a way to make money. If I accept money for this, then it will turn into more of a responsibility for me, and I don't want that.

But you can support me and the community by e.g. sharing how you use the plugin, sharing your note templates, and so on.

**Reply by stracker-phil** [reply]
lol, I completely get the tax-law point 👏

**Reply by egauthier** [reply]
Where would you like examples?  Here?  The Obsidian Forum? Reddit?

I just started using the plugin yesterday and I'm hooked!!  I haven't even scratched the surface yet....

I've replaced my ugly text links with Buttons in my Daily Note Templater template.  Simple example, but one I've seen asked for Templater a million times.  I couldn't figure out a 'no action' for a meta-bind-button, so below just uses a short sleep action to achieve it.

The variables `yesterday` and `tomorrow` are defined in the template above and outside of this block.  Works like a champ, but I can't get the classes to work to improve the look of the buttons (but I think that is a theme thing).

Vielen Dank!!!

````
`BUTTON[button-yesterday]`  ⬅  `BUTTON[button-today]` ➡ `BUTTON[button-tomorrow]`
```meta-bind-button
style: primary
label: Yesterday
hidden: true
class: date-button-yesterday
id: button-yesterday
actions:
  - type: open
    link: "[[<% yesterday %>]]"
```
```meta-bind-button
style: primary
label: Today
hidden: true
class: date-button-today
id: button-today
actions:
  - type: sleep
    ms: 200
```
```meta-bind-button
style: primary
id: button-tomorrow
class: date-button-tomorrow
label: Tomorrow
hidden: true
actions:
 - type: open
   link: "[[<% tomorrow %>]]"
```
````
