### ISSUE TITLE
Inline button with hidden YML block renders an error in reading mode

### ISSUE THREAD

**Issue by AmmarCodes** [mProjectsCode/obsidian-meta-bind-plugin#207]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [ ] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

0.12.0

### Describe the Issue

When adding an inline button and add its YAML definition with `hidden: true` property, it will render an error in the place of the YAML definition, clicking that definition will show the attached modal about having duplicated ID that already exists.

![image](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/351256/01d8bfd6-7e67-4199-94db-43ea803994b2)

### Steps to Reproduce

- Create a new file
- Paste the following code block (copied over from the [docs site](https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/guides/buttons/#inline-buttons)):

`````
Meta Bind has an in plugin help page. `BUTTON[help-button]` Isn't that cool?

```meta-bind-button
style: primary
label: Meta Bind Help
id: help-button
hidden: true
action:
  type: command
  command: obsidian-meta-bind-plugin:open-faq
```
`````

Open the page in **reading mode** and observe the error.

### Expected Behavior

The expected behavior is to not render the error instead of the YAML definition but render nothing if there's no real issue.

P.S. Thanks for the great plugin!
