### ISSUE TITLE
Access button properties in js

### ISSUE THREAD

**Issue by finnBsch** [mProjectsCode/obsidian-meta-bind-plugin#242]
### Describe the Feature you'd Like

It would be nice if one could parameterize a button and pass that to the .js that's being executed.

E.g.:
```
```meta-bind-button
style: default
label: MyButton
myProperty: propertyValue
action:
  type: "js"
  file: myJS.js
```
```
And then enable myJS.js to access the value of myProperty (or all properties of the button) somehow, such that one can easily provide a functionality by JS and configure it via parameter.

### Additional Context

_No response_
