### ISSUE TITLE
Buttons shifter (with icon / without icon)

### ISSUE THREAD

**Issue by dxcore35** [mProjectsCode/obsidian-meta-bind-plugin#308]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.0

### Describe the Issue

![Screenshot 2024-04-23 at 14 33 16](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/7279156/7bf8ba08-5398-45fe-a251-f3d54dd04f05)

### Steps to Reproduce

```
label: 🧮 Summarize
icon: ""
hidden: false
class: ""
tooltip: ""
id: action-summarize
style: destructive
actions:
  - type: command
    command: workspace:export-pdf

```

```
label: Open calendar
icon: calendar
hidden: false
class: ""
tooltip: Log virtue
id: action-calendar
style: default
actions:
  - type: command
    command: obsidian-full-calendar:full-calendar-open

```

And you will see there are not is same line.

### Expected Behavior

Button are identical in sence they have same dimmension and same padding and margins.
