### ISSUE TITLE
Checkbox input field

### ISSUE THREAD

**Issue by Tokumei-54** [mProjectsCode/obsidian-meta-bind-plugin#316]
### Describe the Feature you'd Like

I would like to view toggle inputs as checkboxes or have a separate checkbox input

**Comment by Cube707** [comment]
I was curious about this and implemented a quick and dirty version of this.

These CSS styles are enough to implement a simple checkbox version of the toggle. All you need to do is to assigne the class to the input elment.

```css
.checkbox {
    .checkbox-container {
        aspect-ratio: 1;
        width: unset;
        &::after {
            opacity: 0;
            transform: unset;
            left: 2px;
            mask-size: contain;
            mask-position: center;
            mask-image: url('data:image/svg+xml,<%3Fxml version="1.0" encoding="utf-8"%3F><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools --><svg fill="%23000000" width="800px" height="800px" viewBox="-3.5 0 19 19" xmlns="http://www.w3.org/2000/svg" class="cf-icon-svg"><path d="M4.63 15.638a1.028 1.028 0 0 1-.79-.37L.36 11.09a1.03 1.03 0 1 1 1.58-1.316l2.535 3.043L9.958 3.32a1.029 1.029 0 0 1 1.783 1.03L5.52 15.122a1.03 1.03 0 0 1-.803.511.89.89 0 0 1-.088.004z"/></svg>');
        }
        &.is-enabled::after {
            opacity: 1;
        }
    }
}
```

### Demo:

| Markdown | Renders to |
| --- | --- |
| `` `INPUT[toggle(class(checkbox)):exampleToggle]` toggle stuff`` | ![Image](https://github.com/user-attachments/assets/afcb6037-dc65-4e26-baa9-711b86019093) <br>![Image](https://github.com/user-attachments/assets/25030a90-30a0-42b1-8cd6-94aa0c61cbd1) |

**Comment by ghdoca** [comment]
+1

**Comment by Cube707** [comment]
@greenship24 it is the `.checkbox-container` class actually, you probably targeted the `:after` by accident, which is the chekmark. 

like this:
```css
.checkbox {
    .checkbox-container {
        aspect-ratio: 1;
		background-color: hotpink;
        width: unset;
        &::after {
            opacity: 0;
            transform: unset;
            left: 2px;
            mask-size: contain;
            mask-position: center;
            mask-image: url('data:image/svg+xml,<%3Fxml version="1.0" encoding="utf-8"%3F><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools --><svg fill="%23000000" width="800px" height="800px" viewBox="-3.5 0 19 19" xmlns="http://www.w3.org/2000/svg" class="cf-icon-svg"><path d="M4.63 15.638a1.028 1.028 0 0 1-.79-.37L.36 11.09a1.03 1.03 0 1 1 1.58-1.316l2.535 3.043L9.958 3.32a1.029 1.029 0 0 1 1.783 1.03L5.52 15.122a1.03 1.03 0 0 1-.803.511.89.89 0 0 1-.088.004z"/></svg>');
        }
        &.is-enabled::after {
            opacity: 1;

        }
    }
}
```

<img width="158" height="59" alt="Image" src="https://github.com/user-attachments/assets/7c489e76-9266-42ec-ab18-4adaba283958" />

**Comment by greenship24** [comment]
@Cube707 Actually I wanted to do it in the after. Basically just have it be transparent as it is before it's checked then color in the container. Unsure if that is possible.

If not, your solution is perfectly workable (just an easy way to differentiate two toggles that are by each other.)

**Comment by Cube707** [comment]
@greenship24 sorry for the misunderstanding. If you want the color to only be there when the box is checked, move the background color under the `.is-enabled` block. Like this:

```css
.checkbox {
    .checkbox-container {
        aspect-ratio: 1;
        width: unset;
        &::after {
            opacity: 0;
            transform: unset;
            left: 2px;
            mask-size: contain;
            mask-position: center;
            mask-image: url('data:image/svg+xml,<%3Fxml version="1.0" encoding="utf-8"%3F><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools --><svg fill="%23000000" width="800px" height="800px" viewBox="-3.5 0 19 19" xmlns="http://www.w3.org/2000/svg" class="cf-icon-svg"><path d="M4.63 15.638a1.028 1.028 0 0 1-.79-.37L.36 11.09a1.03 1.03 0 1 1 1.58-1.316l2.535 3.043L9.958 3.32a1.029 1.029 0 0 1 1.783 1.03L5.52 15.122a1.03 1.03 0 0 1-.803.511.89.89 0 0 1-.088.004z"/></svg>');
        }
        &.is-enabled {
			background-color: hotpink;
			&::after {
				opacity: 1;
			}
		}
    }
}
```
