### ISSUE TITLE
Custom Labels for progressBar

### ISSUE THREAD

**Issue by SilverFang13** [mProjectsCode/obsidian-meta-bind-plugin#321]
### I would like to have a way to replace the labels used for the progressBar

![pogressBar](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/151080138/9236a366-4de0-461e-8a02-6e29d6e855f6)

<details>

<summary>Example of a possible syntax</summary>

<p>

'''meta-bind

INPUT[progressBar(
> title(Battery), minValue(0, ":LiBatteryLow:"), maxValue(100, ":LiBatteryFull:"), stepSize(5)):2024-05-14#daily.stats.battery]

'''

</p>

</details> 

### Ability to produce something similar to the following image

![progressBarWithIcons](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/assets/151080138/ade12aca-0b01-46f8-8d1c-019a2d7cbd7a) <sup>*mock up created in [photopea](https://www.photopea.com/)</sup>

**Comment by Cube707** [comment]
you can already accomplish this with CSS, if you have a font loaded which contains the icons or grab the SVG-data directly from <lucide.dev>.

Here is the CSS for using the svg-data:

```css
.mb-input-type-progressBar.battery-charge {
    .mb-progress-bar-label-left,
    .mb-progress-bar-label-right {
        width: 1em;
        aspect-ratio: 1;
        overflow: hidden;
        &::before {
            content: '';
            width: 1em;
            aspect-ratio: 1;
            display: block;
            background: var(--text-normal);
            mask-position: center;
            mask-size: contain;
            mask-repeat: no-repeat;
        }
    }
    .mb-progress-bar-label-left::before {
        mask-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWJhdHRlcnktbG93LWljb24gbHVjaWRlLWJhdHRlcnktbG93Ij48cmVjdCB3aWR0aD0iMTYiIGhlaWdodD0iMTAiIHg9IjIiIHk9IjciIHJ4PSIyIiByeT0iMiIvPjxsaW5lIHgxPSIyMiIgeDI9IjIyIiB5MT0iMTEiIHkyPSIxMyIvPjxsaW5lIHgxPSI2IiB4Mj0iNiIgeTE9IjExIiB5Mj0iMTMiLz48L3N2Zz4=");
    }
    .mb-progress-bar-label-right::before {
        mask-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWJhdHRlcnktZnVsbC1pY29uIGx1Y2lkZS1iYXR0ZXJ5LWZ1bGwiPjxyZWN0IHdpZHRoPSIxNiIgaGVpZ2h0PSIxMCIgeD0iMiIgeT0iNyIgcng9IjIiIHJ5PSIyIi8+PGxpbmUgeDE9IjIyIiB4Mj0iMjIiIHkxPSIxMSIgeTI9IjEzIi8+PGxpbmUgeDE9IjYiIHgyPSI2IiB5MT0iMTEiIHkyPSIxMyIvPjxsaW5lIHgxPSIxMCIgeDI9IjEwIiB5MT0iMTEiIHkyPSIxMyIvPjxsaW5lIHgxPSIxNCIgeDI9IjE0IiB5MT0iMTEiIHkyPSIxMyIvPjwvc3ZnPg==");
    }
}
```
Using that, 

```md
~~~meta-bind
INPUT[progressBar(title(Battery),class(battery-charge)):exampleProperty]
~~~
```
Renders to:

![Image](https://github.com/user-attachments/assets/cf77b79c-37d6-4fd1-b2f6-0b736d3d641e)
