### ISSUE TITLE
Buttons not displaying since Obsidian v1.6.3

### ISSUE THREAD

**Issue by tobischiebel** [mProjectsCode/obsidian-meta-bind-plugin#348]
### Please fill out these Check-boxes

- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### This Issue Occurs on

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Plugin Version

1.1.1

### Describe the Issue

Any Codeblock buttons are no longer displayed at all in neither preview or view mode since the Obsidian v1.6.3 update on Windows.
Also tested on Android on Obsidian 1.5.12, where the buttons are still displayed as intended.

### Steps to Reproduce

1. Create a new note with property to update, e.g. "foo" with value 0.
2. Create button, e.g. to id "test"
````
```meta-bind-button
label: "This is a test"
hidden: true
id: "test"
style: default
actions:
  - type: updateMetadata
    bindTarget: foo
    evaluate: false
    value: 69
```
````
3. Create BUTTON in code block e.g. with binding to id "test"
```meta-bind
BUTTON[test]
```
4. Use (pre)view mode where the button is not to be seen.

### Expected Behavior

The button is visible
