### ISSUE TITLE
allow referencing other properties in the update metadata button action

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-meta-bind-plugin#358]

**Comment by mProjectsCode** [comment]
currently only possible by utilizing JavaScript, either via a button action that can run JS (and then use the MB API) or crating the button dynamically similar to the advanced examples in the docs

**Comment by mProjectsCode** [comment]
implemented with a `getMetadata(bindTarget)` function that you can pass a bind target sting.

Example:
```yaml
label: "Add count to count2"
hidden: false
style: default
actions:
  - type: updateMetadata
    bindTarget: count2
    evaluate: true
    value: "x + getMetadata('count')"
```
