### ISSUE TITLE
Replace Self not working after templater conversion

### ISSUE THREAD

**Issue by SandmansDreams** [mProjectsCode/obsidian-meta-bind-plugin#404]
### Please fill out these Check-boxes

- [X] I checked for existing similar issues
- [X] I checked that the plugin is up to date
- [X] The issue persist with all other plugins and themes disabled

### Plugin Version

1.1.3

### This Issue Occurs on

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 23.6.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Spectrum Blue v1.0.0
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 43
	Plugins enabled: 2
		1: Meta Bind v1.1.3
		2: Templater v2.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

When using a multi-action button and having the replaceself function, it only works (gets rid of the button) if the command function is run after the replaceself function. In this case it is a command for templater to replace the active templates in the file. Seems to work fine with other commands including other templater commands.

### Steps to Reproduce

Run this button:
```meta-bind-button
label: Templater Converter
icon: replace
hidden: false
class: ""
tooltip: Converts the template into a usable file.
id: TemplateConvert
style: destructive
actions:
  - type: replaceInNote
    fromLine: 3
    toLine: 3
    replacement: "tags:: #"
  - type: replaceInNote
    fromLine: 4
    toLine: 4
    replacement: "parent:: "
  - type: command
    command: templater-obsidian:replace-in-file-templater
  - type: replaceSelf
    replacement: ""
```

This button works (flipped the locations of the replaceself and templater converter):
```meta-bind-button
label: Templater Converter
icon: replace
hidden: false
class: ""
tooltip: Converts the template into a usable file.
id: TemplateConvert
style: destructive
actions:
  - type: replaceInNote
    fromLine: 3
    toLine: 3
    replacement: "tags:: #"
  - type: replaceInNote
    fromLine: 4
    toLine: 4
    replacement: "parent:: "
  - type: replaceSelf
    replacement: ""
  - type: command
    command: templater-obsidian:replace-in-file-templater
```

### Expected Behavior

The second button functions as expected. The first button does everything except the replaceself command.

**Comment by mProjectsCode** [comment]
I haven't looked at this closely, but my first guess is that Obsidians metadata cache (where I am pulling the line positions from) has not updated yet, so the line positions are wrong.

**Comment by SandmansDreams** [comment]
> I haven't looked at this closely, but my first guess is that Obsidians metadata cache (where I am pulling the line positions from) has not updated yet, so the line positions are wrong.

Hmm that could make sense. It does not appear to remove any other lines, just seems to not happen. But could still be the case.

**Comment by mProjectsCode** [comment]
Does any error appear in the console?

**Comment by SandmansDreams** [comment]
> Does any error appear in the console?

As far as I can tell, no. There were several errors before I cleared it and then ran the button. However, none of these errors seem to pertain to the button.
<img width="557" alt="image" src="https://github.com/user-attachments/assets/00150620-d319-4b16-a772-4ee24a2b987a">

**Comment by SKiltzer** [comment]
I encountered this last night when configuring a button and, while not exactly elegant, I found a workaround.
Before and after declaring the command action:
```
  - type: command
    command: templater-obsidian:replace-in-file-templater
```
Place a 10ms sleep action before, and another after. This provides enough time for the system to evaluate the actions and pass them without issues. Tested in my own instance, this was what worked in your specific case (only change i made were the line numbers i was replacing)

```
label: Templater Converter
icon: replace
hidden: false
class: ""
tooltip: Converts the template into a usable file.
id: TemplateConvert
style: destructive
actions:
  - type: replaceInNote
    fromLine: 3
    toLine: 3
    replacement: "tags:: #"
  - type: replaceInNote
    fromLine: 4
    toLine: 4
    replacement: "parent:: "
  - type: sleep
    ms: 10
  - type: command
    command: templater-obsidian:replace-in-file-templater
  - type: sleep
    ms: 10
  - type: replaceSelf
    replacement: ""
```
