### ISSUE TITLE
Allow templater strings in button templates

### ISSUE THREAD

**Issue by andresatierf** [mProjectsCode/obsidian-meta-bind-plugin#406]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I think there is a lot of potential to button templates, but is hard to make them generic.

### Describe the Feature you'd like

I would like for it to be possible to add templater code inside the button templates.

The below example would be a button that allows users of daily notes to navigate to the next day note 
```
label: Tomorrow
hidden: false
id: go-to-tomorrow
style: destructive
actions:
  - type: open
    link: "<% '[[journal/daily/' + moment(tp.file.title).subtract(1, 'day').format('YYYY-MM-DD') + ']]' %>"
```

### Alternatives

I think this is a good alternative to #317
