### ISSUE TITLE
Button Action: open

### ISSUE THREAD

**Issue by ifulou** [mProjectsCode/obsidian-meta-bind-plugin#444]
### Page

https://www.moritzjung.dev/obsidian-meta-bind-plugin-docs/reference/buttonactions/open/

### Issue or Enhancement

When I use a button to open specific note,  wikilink ([[note]]) dosen't work.
````
```meta-bind-button
style: primary
label: open mynote
action: 
 type: open
 link: [[mynote]]
```
````

**Comment by mProjectsCode** [comment]
Put quotes around your link.
````
```meta-bind-button
style: primary
label: open mynote
action: 
 type: open
 link: "[[mynote]]"
```
````
