### ISSUE TITLE
Allow "Open link" button types to navigate to sections within current note without need for stating note name explicitly

### ISSUE THREAD

**Issue by hdsateyate** [mProjectsCode/obsidian-meta-bind-plugin#450]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

At the moment the "Open link" button does not allow navigation within the current note in the way you would navigate by clicking `[[#Section]]`

### Describe the Feature you'd like

Allow "Open link" button type to navigate to section within current note without specifying the note name (such that it can be used in a template without needing to reference the note name).

### Alternatives

N/A

### Additional Context

What I am currently doing alongside my other buttons is writing a section of plain markdown which renders as clickable links but I would prefer for them all to be buttons:

<img width="561" alt="image" src="https://github.com/user-attachments/assets/e1fde1f4-de09-4146-a12c-54e289bf7757">

<img width="754" alt="image" src="https://github.com/user-attachments/assets/c73411b0-681e-4a86-afb0-2daff11c8805">

**Comment by mProjectsCode** [comment]
This seems like an oversight on my part, as it works with normal wiki links but not with the open action. I will investigate.

**Comment by mProjectsCode** [comment]
Links to headings like `[[#heading]]` work, but sections like `[[#^section-id]]` do not.

**Comment by mProjectsCode** [comment]
After a small fix to the markdown link parser to support section links, the following examples both work.

```yaml
label: Scroll to Bottom
style: default
actions:
  - type: open
    link: "[[#This is a Heading at the Bottom]]"
    newTab: false

```

```yaml
label: Scroll to Labeled Section
style: default
actions:
  - type: open
    link: "[[#^section-1]]"
    newTab: false

```
