### ISSUE TITLE
parsing of YAML dictionaries 

### ISSUE THREAD

**Issue by simonfossom** [mProjectsCode/obsidian-meta-bind-plugin#463]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

view field can display property but it cannot parse YAML dict as far as I figured.

### Describe the Feature you'd like

For frontmatter with dictionary entries, I'd like to display them with view field.

In following example: `view[{page#tasks/&id-123456/title}<br>{page#tasks/&id-123456/description}][text{rendermarkdown}]` or something like that.

```yaml
tasks:
  - &id-123456
    title: "Complete project report"
    due: "2024-12-01"
    start: "2024-11-20"
    created: "2024-11-15"
    completed: "2024-11-21"
    description: |
      Prepare the final draft of the project report.
      Ensure all sections are proofread and approved by the team.
  - &id-asdfgh
    title: "Plan team meeting"
    due: "2024-11-25"
    start: "2024-11-22"
    created: "2024-11-18"
    completed: ""
    description: |
      "Organize a meeting to discuss the next quarter's objectives."
      Confirm availability of all team members.
    dependsOn: *id-123456
```

### Alternatives

none really. even with Dataview it's complex query to do.
