### ISSUE TITLE
Mark `canary` releases as `prerelease`

### ISSUE THREAD

**Issue by marcaddeo** [mProjectsCode/obsidian-meta-bind-plugin#478]
### Please fill out these Check-boxes

- [X] I checked for existing similar feature requests
- [X] I have read the docs and checked that the feature I am requesting is not already implemented
- [X] My feature request consists of only one feature

### Is your Feature Request related to a Problem or Annoyance?

I use [obsidian-plugin-update-tracker](https://github.com/swar8080/obsidian-plugin-update-tracker) to track plugin updates, and it works well. However, your plugin does not mark canary releases as prerelease, so the update tracking plugin can't filter them out as "beta" releases.

### Describe the Feature you'd like

I would like it if canary releases were marked as prerelease so they can easily be filtered from actual releases.

**Comment by mProjectsCode** [comment]
Sounds good, but I don't know how I would do that. I am using a GH action to create the releases. There is [an option for prereleases](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/e21434f82213c46522f9e4cd99e1e3f03101c044/.github/workflows/release.yml#L43), but idk how to set this based on the version number.

**Comment by marcaddeo** [comment]
> Sounds good, but I don't know how I would do that. I am using a GH action to create the releases. There is [an option for prereleases](https://github.com/mProjectsCode/obsidian-meta-bind-plugin/blob/e21434f82213c46522f9e4cd99e1e3f03101c044/.github/workflows/release.yml#L43), but idk how to set this based on the version number.

You can do something like this with GitHub Actions:

```yaml
- name: Determine prerelease status
  id: status
  run: |
    if [[ "${{ github.ref }}" == *"canary"* ]]; then
      echo "prerelease=true" >> $GITHUB_OUTPUT
    else
      echo "prerelease=false" >> $GITHUB_OUTPUT
    fi

- name: Create Release
  id: create_release
  uses: actions/create-release@v1
  env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.ref }}
  with:
      tag_name: ${{ github.ref }}
      release_name: ${{ github.ref }}
      draft: false
      prerelease: ${{ steps.status.outputs.prerelease }}
```

Untested, but should be something like that. Alternatively, you can update this:

```yml
on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - '*' # Push events to matching any tag format, i.e. 1.0, 20.15.10
```

To exclude canary tags, but obviously then there's no canary releases and I don't know what purposes you're using them for so that's probably not a good solution :)
