### ISSUE TITLE
View field with text(renderMarkdown) for a button puts updated value in new row

### ISSUE THREAD

**Issue by Acenoid** [mProjectsCode/obsidian-meta-bind-plugin#502]
### Please fill out these Check-boxes

- [x] I checked for existing similar issues
- [x] I checked that the plugin is up to date
- [x] The issue persists with all other plugins and themes disabled

### Plugin Version

1.3.1

### This Issue Occurs on

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Meta Bind v1.3.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

1. A view field with text(renderMarkdown) puts updated value into a new row instead of overwriting itself
2. The number is shown only temporarily - after reopening the note the correct value will be shown.

![Image](https://github.com/user-attachments/assets/aa47f7aa-5b77-4694-8279-0030da924bfe)

### Steps to Reproduce

Example to reproduce the issue.
```
---
Version: 0
---

works:
`VIEW[{Version}][text()]`

does not work:
`VIEW[**<center>{Version}</center>**][text(renderMarkdown)]`

Button:  `BUTTON[Version-increment]`

Button Code: 
~~~meta-bind-button
label: "+1"
id: Version-increment
hidden: true
style: primary
actions:
  - type: updateMetadata
    bindTarget: Version
    evaluate: true
    value: 1 + getMetadata('Version')
tooltip: Neue Version
~~~
```

### Expected Behavior

1. If RenderMarkdown is applied , the button should still updateMetadata and not add extra lines to the note (temporarily).
