### ISSUE TITLE
Create note button fails to open in new tab on ctrl + click

### ISSUE THREAD

**Issue by Graywaren** [mProjectsCode/obsidian-meta-bind-plugin#520]
### Please fill out these Check-boxes

- [x] I checked for existing similar issues
- [x] I checked that the plugin is up to date
- [x] The issue persists with all other plugins and themes disabled

### Plugin Version

1.3.4

### This Issue Occurs on

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.8.7
	Installer version: v1.8.4
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Dataview v0.5.67
		2: Meta Bind v1.3.4
		3: JS Engine v0.3.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

I have a button that creates a note with the options of "open note" and "open if note already exists" both enabled. This type of button doesn't have the option of open in new tab, so I tried to ctr + click the button like I can on other buttons and links to open it in a new tab. Unfortunately this doesn't work. The file creates or opens in the same tab. This is also the case for a create note with templater file button

Here's an example button made in the example vault:
```
label: testing in test
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: createNote
    folderPath: Test
    fileName: Testing
    openNote: true
    openIfAlreadyExists: true

```

### Steps to Reproduce

Create a button that creates a new note with the "open note" and "open if note already exists" both enabled. Ctr + click on button.

### Expected Behavior

I'd expect it to open in a new tab
