### ISSUE TITLE
Create note button fails to open existing note in root folder level

### ISSUE THREAD

**Issue by Graywaren** [mProjectsCode/obsidian-meta-bind-plugin#521]
### Please fill out these Check-boxes

- [x] I checked for existing similar issues
- [x] I checked that the plugin is up to date
- [x] The issue persists with all other plugins and themes disabled

### Plugin Version

1.3.4

### This Issue Occurs on

- [x] Windows
- [ ] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS

### Debug Info

```text
SYSTEM INFO:
	Obsidian version: v1.8.7
	Installer version: v1.8.4
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 3
		1: Dataview v0.5.67
		2: Meta Bind v1.3.4
		3: JS Engine v0.3.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Describe the Issue

A button set to create a note with the option of "open note if already exists" enabled set to create the note in the "/" level of the vault will not open an existing note of the same name and instead just creates a new note with the running number scheme. It works properly when creating a note within a folder, but at the top level it always creates a new note.

For example this just creates the notes "Testing" then "Testing 1", "Testing 2" etc.
```
label: test in root
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: createNote
    folderPath: /
    fileName: Testing
    openNote: true
    openIfAlreadyExists: true
```

but this works fine:

```
label: testing in test
icon: ""
style: default
class: ""
cssStyle: ""
backgroundImage: ""
tooltip: ""
id: ""
hidden: false
actions:
  - type: createNote
    folderPath: Test
    fileName: Testing
    openNote: true
    openIfAlreadyExists: true
```

Both of these were created in the example vault with the button builder

### Steps to Reproduce

Make a button set to create a note of a specified title in the top level of the vault with the option of "open note if already exists" enabled.
Click button twice

### Expected Behavior

I would expect the already existing note to be opened.
